markdown: rdiscount
brooklyn-version: 0.5.0-M1 # BROOKLYN_VERSION
brooklyn-snapshot-git-branch: master   # if line above is SNAPSHOT this should point to corresponding git branch (e.g. master, 0.4)
brooklyn-root-url: /
url: /v/0.5.0-M1  # BROOKLYN_VERSION
